In [2]:
import pandas as pd
import numpy as np

In [4]:
pip install meteostat

Collecting meteostat
  Downloading meteostat-1.6.8-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: pandas>=1.1 in /opt/anaconda3/lib/python3.11/site-packages (from meteostat) (2.2.2)
Requirement already satisfied: pytz in /opt/anaconda3/lib/python3.11/site-packages (from meteostat) (2024.1)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.11/site-packages (from meteostat) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.11/site-packages (from pandas>=1.1->meteostat) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.11/site-packages (from pandas>=1.1->meteostat) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=1.1->meteostat) (1.16.0)
Downloading meteostat-1.6.8-py3-none-any.whl (31 kB)
Installing collected packages: meteostat
Successfully installed meteostat-1.6.8
Note: you may need to restart the kernel to use updated packages.

In [6]:
import meteostat as mt

In [14]:
st = mt.Stations().fetch()

In [16]:
st.head()

,name,country,region,wmo,icao,latitude,longitude,elevation,timezone,hourly_start,hourly_end,daily_start,daily_end,monthly_start,monthly_end
id,,,,,,,,,,,,,,,
00FAY,Holden Agdm,CA,AB,71227,CXHD,53.1900,-112.2500,688.0,America/Edmonton,2020-01-01,2024-10-18,2002-11-01,2024-03-13,2003-01-01,2022-01-01
00TG6,Athabasca 1,CA,AB,<NA>,<NA>,54.7200,-113.2900,515.0,America/Edmonton,NaT,NaT,2000-01-01,2022-07-12,2000-01-01,2010-01-01
01001,Jan Mayen,NO,<NA>,01001,ENJA,70.9333,-8.6667,10.0,Europe/Oslo,1931-01-01,2024-08-20,1921-12-31,2024-09-24,1922-01-01,2022-01-01
01002,Grahuken,NO,SJ,01002,<NA>,79.7833,14.4667,0.0,Europe/Oslo,1986-11-09,2024-08-20,2010-10-07,2020-08-17,NaT,NaT
01003,Hornsund,NO,<NA>,01003,<NA>,77.0000,15.5000,10.0,Europe/Oslo,1985-06-01,2024-08-20,2009-11-26,2020-08-31,2016-01-01,2017-01-01

In [26]:
us = st[st['country']=='US']

In [28]:
us.head()

,name,country,region,wmo,icao,latitude,longitude,elevation,timezone,hourly_start,hourly_end,daily_start,daily_end,monthly_start,monthly_end
id,,,,,,,,,,,,,,,
04AEH,Norwich,US,NY,<NA>,KOIC,42.5665,-75.5242,312.0,America/New_York,2022-04-23,2024-10-18,2022-04-23,2022-04-26,NaT,NaT
0MV8M,Hill Air Force Base,US,UT,<NA>,KHIF,41.1111,-111.9623,1459.0,America/Denver,2022-04-23,2024-10-18,2022-04-23,2022-04-25,NaT,NaT
0NNEW,Effingham County Memorial Airport,US,IL,<NA>,K1H2,39.0706,-88.5333,179.0,America/Chicago,2022-05-06,2024-10-18,NaT,NaT,NaT,NaT
0OBKP,Live Oak County Airport,US,TX,<NA>,K8T6,28.3628,-98.1165,39.0,America/Chicago,2022-05-06,2024-10-18,NaT,NaT,NaT,NaT
0RJDR,Hotel (Gurley),US,NE,<NA>,K1HW,41.3200,-102.8300,1263.0,America/Denver,2022-05-06,2024-10-18,NaT,NaT,NaT,NaT

In [30]:
us['region'].unique()

<StringArray>
['NY', 'UT', 'IL', 'TX', 'NE', 'LA', 'OK', 'VA', 'SC', 'KS', 'NM', 'OR', 'NC',
 'AK', 'WY', 'WA', 'MT', 'CO', 'MS', 'ND', 'IN', 'FL', 'NH', 'MN', 'OH', 'CA',
 'AR', 'VT', 'NV', 'AZ', 'WV', 'MI', 'GA', 'AL', 'TN', 'MO', 'MD', 'PA', 'DC',
 'NJ', 'KY', 'DE', 'CT', 'MA', 'RI', 'IA', 'ID', 'ME', 'WI', 'SD', <NA>, 'HI',
 'RO', 'SA', 'TI', 'WQ']
Length: 56, dtype: string

In [32]:
ca = us[us['region']=='CA']

In [34]:
ca.head()

,name,country,region,wmo,icao,latitude,longitude,elevation,timezone,hourly_start,hourly_end,daily_start,daily_end,monthly_start,monthly_end
id,,,,,,,,,,,,,,,
69002,Hunter Ligget / Hunter-Liggett,US,CA,69002,KHGT,35.9935,-121.2367,310.0,America/Los_Angeles,1964-07-15,1997-04-01,1964-07-15,1971-07-31,1964-01-01,1971-01-01
69007,Fort Ord / Blanco,US,CA,69007,KOAR,36.6815,-121.7617,42.0,America/Los_Angeles,1973-01-02,2024-10-18,1983-03-31,2022-04-25,2020-01-01,2022-01-01
69014,Irvine,US,CA,69014,KNZJ,33.6667,-117.7167,119.0,America/Los_Angeles,1989-01-01,1999-06-06,1945-03-01,1998-12-10,1945-01-01,1998-01-01
69015,Twentynine Palms / Sunfair Heights,US,CA,69015,KNXP,34.2962,-116.1622,625.0,America/Los_Angeles,1990-01-02,2024-10-18,1945-05-01,2022-04-24,1945-01-01,2021-01-01
69542,Monterey / Del Monte,US,CA,69542,KQNM,36.5900,-121.8600,152.0,America/Los_Angeles,2001-11-01,2002-08-20,NaT,NaT,NaT,NaT

In [36]:
ca.info()

<class 'pandas.core.frame.DataFrame'>
Index: 163 entries, 69002 to ZGK9P
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           163 non-null    object
 1   country        163 non-null    string
 2   region         163 non-null    string
 3   wmo            53 non-null     string
 4   icao           159 non-null    string
 5   latitude       163 non-null    float64
 6   longitude      163 non-null    float64
 7   elevation      163 non-null    float64
 8   timezone       163 non-null    string
 9   hourly_start   159 non-null    datetime64[ns]
 10  hourly_end     159 non-null    datetime64[ns]
 11  daily_start    154 non-null    datetime64[ns]
 12  daily_end      154 non-null    datetime64[ns]
 13  monthly_start  138 non-null    datetime64[ns]
 14  monthly_end    138 non-null    datetime64[ns]
dtypes: datetime64[ns](6), float64(3), object(1), string(5)
memory usage: 20.4+ KB

In [48]:
ca['name'].unique()

array(['Hunter Ligget / Hunter-Liggett', 'Fort Ord / Blanco', 'Irvine',
       'Twentynine Palms / Sunfair Heights', 'Monterey / Del Monte',
       'Santa Monica Municipal Airport', 'Stevenson Ranch',
       'El Centro, Naval Air Facility',
       'Riverside / March Air Force Base', 'Burbank-Glendale-Pasadena',
       'Mount Wilson', 'San Diego International Airport',
       'San Nicolas Island', 'Avalon Catalina Airport', 'MCAS Miramar',
       'Los Angeles Airport', 'Long Beach Airport',
       'Needles / Parker Junction', 'Edwards Air Force Base',
       'Palmdale Prod Flight Plant', 'Sandberg',
       'Bakersfield Meadows Field', 'Fresno Air Terminal',
       'Point Piedras Blanca', 'Nawcwpns Point Mugu, Ca',
       'Santa Barbara / La Patera', 'Lompoc, Vandenberg Air Force Base',
       'Santa Maria Public Airport', 'Bishop Airport',
       'Merced / Castle Air Force Base', 'Leisure Town',
       'Sacramento Executive Airport', 'Monterey / Naf, Ca.',
       'Stockton Metropolitan Airport',
       'Metro Oakland International  Airport', 'San Francisco Airport',
       'Farallon Island', 'Chico', 'Susanville / Johnstonville',
       'Hayward / Russell City', 'Red Bluff Municipal Airport',
       'Redding Municipal Airport', 'Salinas / Spreckels Junction',
       'Eureka', 'Beale Afb / Oroville Junction', 'Sheridan, Ca',
       'Monterey / Pacific Grove Acres', 'Alameda Naval Air Station',
       'Moffett Field', 'Fairfield / Travis Air Force Base',
       'Fort Irwin/Barstow, Bicycle Lake Army Airfield',
       'Naws China Lake', 'Cuddleback Gunnery Range',
       'Lemoore Naval Air Station', 'Ontario International Airport',
       'Concord Buchanan Field', 'Auburn Municipal Airport',
       'Montague / Horizon Hills Mobile Home Park',
       'Edwards Afb / North Edwards', 'Alturas / Juniper',
       'Arcata / Clam Beach', 'Corona', 'Napa / Middleton',
       'Apple Valley / Bell Mountain', 'Bridgeport / Sonora Junction',
       'Blythe / Mesa Verde', 'Blue Canyon', 'Byron',
       'Cable Arpt / College Heights',
       'Crescent City / Crescent City North', 'Camarillo / Springville',
       'Chino', 'San Andreas / Fourth Crossing',
       'Los Angeles / Jefferson',
       'Carlsbad / Rancho Carlsbad Trailer Park',
       'Hollister / Cottage Corners', 'Campo', 'Daggett / Minneola',
       'Delano / Delano Mobile Home Park', 'Novato / Burdell',
       'Davis / Plainfield', 'San Martin',
       'Davis / Briggston (Historical)', 'El Monte / Hayes',
       'Murrieta/Temecula / Murrieta Hot Springs (Historical)',
       'Fresno / West Park', 'Fortuna / Alton', 'Fullerton / Fuller Park',
       'Grass Valley / Forest Knolls', 'Palmdale / El Mirage',
       'Half Moon Bay / El Granada Mobile Home Park',
       'Hawthorne / Cypave', 'Hanford / Shell', 'Hemet / Egan',
       'Imperial', 'Inyokern', 'Santa Ynez', 'Jackson / Sutter Hill',
       'Borrego Springs', 'Fallbrook / Deluz', 'Big Bear City',
       'Oceano / Oceano Beach', 'Lincoln / Ewing', 'Lemoore / Marnett',
       'Livermore / East Pleasanton', 'Madera / Notarb',
       'Sacramento / McClellan Park', 'Merced',
       'Sacramento / Mather Field', 'Mojave / Chaffee',
       'Mammoth / Whitmore Hot Springs', 'Modesto City / Riverside',
       'Marysville / Alicia', 'Oceanside / Chappo', 'Crows Landing / Jet',
       'Imperial Beach', 'San Clemente / Avalon',
       'Oceanside / Las Flores', 'Chester', 'Columbia / Springfield',
       'Weaverville', 'Petaluma / East Petaluma', 'Trinity Center',
       'Oceanside / El Camino 76 Trailer Park', 'Oxnard',
       'Palo Alto / Runnymeade (Historical)', 'La Verne',
       'Paso Robles / Estrella', 'Palm Springs', 'Porterville / Lois',
       'Placerville / Smithflat', 'Riverside / Arlanza',
       'San Jose / Alum Rock', 'Ramona / Rosemont',
       'San Bernardino / North Norton',
       'San Luis Obispo / Steele (Historical)', 'San Diego / Bandini',
       'San Diego / Town And Country Mobile Home Park',
       'Montague / Snowden', 'San Jose / Santa Clara Trailer Village',
       'Los Alamitos', 'Sacramento / Kiesel', 'Santa Ana / Paularino',
       'San Carlos / Silver Penny Mobile Home Park',
       'Santa Rosa / Shiloh', 'Santa Cruz / Isla Vista',
       'Torrance / Walteria', 'Truckee / Polaris', 'Thermal',
       'South Lake Tahoe / Tahoe Valley', 'Ukiah / Asylum',
       'Visalia / Midvalley', 'Van Nuys / Raymer',
       'Los Angeles / Pacoima', 'Lancaster / Antelope Acres',
       'Watsonville / Monterey Vista Mobile Home Park', 'Mount Shasta',
       'Monterey Regional Airport', 'Tehachapi Municipal Airport',
       'Tracy Municipal Airport', 'Lompoc Airport', 'Julian CDF',
       'Victorville Airport'], dtype=object)

0

In [ ]:
import requests
import pandas as pd

# Set parameters for the API request
params = {
    'latitude': 37.7749,  # San Francisco latitude
    'longitude': -122.4194,  # San Francisco longitude
    'start_date': '2023-01-01',
    'end_date': '2023-12-31',
    "hourly": ["temperature_2m", "precipitation", "weather_code", "wind_speed_10m", "wind_direction_10m", "relative_humidity_2m"]
}

# Make the API request
response = requests.get('https://archive-api.open-meteo.com/v1/archive', params=params)

# Check if the request was successful
if response.status_code == 200:
    data = response.json()

    # Convert the 'hourly' section of the response into a DataFrame
    df = pd.DataFrame(data['hourly'])
    
    # Display first few rows of the data
    print(df.head())
    
    # Save the data to a CSV file
    df.to_csv('san_francisco_weather_2023_full.csv', index=False)
else:
    print(f"Failed to retrieve data: {response.status_code}")

In [ ]:
import pandas as pd

# Load the weather data (if not already loaded)
weather_data = pd.read_csv('san_francisco_weather_2023_full.csv')

# Define the weather code mapping
weather_code_mapping = {
    0: 'Clear sky',
    1: 'Mainly clear',
    2: 'Partly cloudy',
    3: 'Overcast',
    45: 'Fog',
    48: 'Depositing rime fog',
    51: 'Light drizzle',
    53: 'Moderate drizzle',
    55: 'Dense drizzle',
    61: 'Slight rain',
    63: 'Moderate rain',
    65: 'Heavy rain',
    66: 'Freezing rain (light)',
    67: 'Freezing rain (heavy)',
    71: 'Slight snow',
    73: 'Moderate snow',
    75: 'Heavy snow',
    95: 'Thunderstorm',
    96: 'Thunderstorm with slight hail',
    99: 'Thunderstorm with heavy hail'
}

# Map the weather codes to their respective descriptions
weather_data['weather_category'] = weather_data['weather_code'].map(weather_code_mapping)

# Split the 'time' column into 'date' and 'hour'
weather_data['date'] = pd.to_datetime(weather_data['time']).dt.date  # Extract the date
weather_data['hour'] = pd.to_datetime(weather_data['time']).dt.hour  # Extract the hour

# Drop the original 'time' column if no longer needed
weather_data = weather_data.drop(columns=['time'])

weather_data['County'] = "San Francisco"

# Reorder columns (optional)
weather_data = weather_data[['date', 'hour', 'temperature_2m', 'precipitation', 
                             'weather_code', 'wind_speed_10m', 'wind_direction_10m', 
                             'relative_humidity_2m', 'weather_category', 'County']]

# Save the updated dataset to a new CSV file
weather_data.to_csv('san_francisco_weather_2023_split.csv', index=False)

# Display first few rows to verify
print(weather_data.head())